### ISSUE TITLE
This might be typo.

### ISSUE THREAD

**Issue by imb19jan9** [lighttransport/nanort#13]
1130th line on nanort.h

`pos = bmin[j] + (i + 0.5f) * bstep[j];`
should be
`pos = bmin[j] + (i + 1.0f) * bstep[j];`

There are some comments above this statement.

      //
      // Split pos bmin + (i + 1) * (bsize / BIN_SIZE)
      // +1 for i since we want a position on right side of the cell.
      //

This comment dosen't correspond to the below line.
I guess one of them is wrong.

**Comment by syoyo** [comment]
Thank you for finding an issue!

Its now fixed.
