### ISSUE TITLE
multi-hit ray traversal

### ISSUE THREAD

**Issue by daeyun** [lighttransport/nanort#33]
I'm trying to implement ray tracing that hits multiple surfaces, instead of just the closest one. So it would be as if the ray penetrates through multiple triangles as it traverses the mesh.

Just to be clear, is this what `MultiHitTraverse` is supposed to do? Looks like it's disabled by default, so I haven't tried it yet. I see that "Fix multi-hit ray traversal." is in the todo list for the project. What problem does it have; is it safe to use?

For now, in order to accomplish what I'm trying to do, I'm increasing `min_t` by a small amount and repeating `Traverse`. But it is slow and doesn't handle cases like two triangles coinciding at the same distance. What's the best way to implement this, at the moment? Thanks in advance for any help you are able to provide.

**Comment by syoyo** [comment]
Please read this: http://jcgt.org/published/0003/01/01/

`MultiHitTraverse` was worked but currently its not working after I've modified API and Internal structure of Traverser.

Easiest way would be manage list of intersections in priority queue by the hit distance(i.e. fix nanort's current `MultiHitTraverse` implementation) according to the above multi hit paper.

**Comment by daeyun** [comment]
Thanks for the quick response! :+1: :sparkles:

**Comment by syoyo** [comment]
PR appreciated if you got success to implement multi hit ray traversal with NanoRT.
