### ISSUE TITLE
Remove inv_dir and dir_sign from Ray class or utilize them

### ISSUE THREAD

**Issue by Tyler799** [lighttransport/nanort#49]
Currently, the comments say they are filled internally. This is incorrect, these members are never either filled or read. Instead, Traverse(), MultiHitTraverse(), and ListNodeIntersections() all create these on the fly to pass to IntersectRayAABB().

Either they should be removed or used, having them there is confusing if they arent used.

**Comment by syoyo** [comment]
Thanks! `inv_dir` and `dir_sign` was used before nanort introduced `Intersector` template class.

I have just removed it.

**Comment by Tyler799** [comment]
You're welcome, thanks for the quick reply.
