### ISSUE TITLE
What is faces : The array of triangle face indices (3 * numFaces)

### ISSUE THREAD

**Issue by kilasuelika** [lighttransport/nanort#71]
I'm confusing about
```
nanort::TriangleMesh<float> triangle_mesh(vertices, faces, /* stride */sizeof(float) * 3);
```
Does `faces` store vertices indices of each triangle? For example, (1,2,3) will mean 3 vertices indices of the first face are 1,2 and 3.

**Comment by syoyo** [comment]
Its actually vertex indices. 

PR of better naming and fixing documents are welcome.

**Comment by kilasuelika** [comment]
> Its actually vertex indices.
> 
> PR of better naming and fixing documents are welcome.

Thank you.
```
template <typename T = float>
class TriangleIntersection {
 public:
  T u;
  T v;

  // Required member variables.
  T t;
  unsigned int prim_id;
};
```
Do you know what are `u` and `v`?

**Comment by kilasuelika** [comment]
> Its actually vertex indices.
> 
> PR of better naming and fixing documents are welcome.

Thank you. I will make some PRs on documentation.

**Comment by syoyo** [comment]
@kilasuelika Rename `faces` to `faceVertexIndices` would be a good candidate. Such a terminology is used in USD  https://graphics.pixar.com/usd/docs/api/class_usd_geom_mesh.html
