### ISSUE TITLE
nanosg. how to remove white rounded border?

### ISSUE THREAD

**Issue by tigrazone** [lighttransport/nanort#80]
![nanosg-white-border](https://user-images.githubusercontent.com/3808839/220119617-da4179f5-c810-4c93-b531-18cca40ebf2a.jpg)

**Comment by syoyo** [comment]
You should describe procedures to reproduce in detail.

**Comment by tigrazone** [comment]
one more question. did nanosg build well in linux and mac os?
my screenshot from windows 10. built with minGW's gcc 11.3.0

**Comment by tigrazone** [comment]
I just built makefile with premake5 gmake and type make.
Have exe file and run it and rounded border is present all the time

**Comment by syoyo** [comment]
Confirmed it happens in Linux. Seems an issue of imgui btgui backend.

btgui backend is deprecated and not recommended to use.

it'd be better to rewrite nanort example codes using well-maintained imgui backend(OpenGL3 or SDLRenderer recommended)

https://github.com/ocornut/imgui/tree/master/examples

You can contribute!

**Comment by tigrazone** [comment]
I think it because of imguizmo. Without it is no rounded border.
I prefer OpenGL3. Sdl port need sdl library. 
Keep it simple!

**Comment by tigrazone** [comment]
And little bit strange position of imguizmo block 72, 72. I dont find where is this position in code

**Comment by syoyo** [comment]
Examples use old imguizmo. The issue may disappear once updating imguizmo with the recent version.
